#stage 1
#Start with a base image containing Java runtime
FROM openjdk:11-slim as build

#ADD Maintainer Info
LABEL maintainer="Mallikarjuna kuruva <arjunflex@gmail.com>"

#The applications jar file
ARG JAR_FILE

# Add the application's jar to the container
COPY ${JAR_FILE} app.jar

#unpackage jar file
RUN mkdir -p target/dependency && (cd target/dependency; jar -xf /app.jar)

#stage 2
#same java run time
FROM openjdk:11-slim

#Add volume pointng to /tmp
VOLUME /tmp

#Copy unpackaged application to new container
ARG DEPENDENCY=/target/depedency
COPY --from=build  ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY --from=build ${DEPENDENCY}/META-INF /app/META-INF
COPY --from=build ${DEPENDENCY}/BOOT-INF/classes /app

#execute the application
ENTRYPOINT ["java","-cp","app:app/lib/*","com.optimagrowth.license.LicenseServiceApplication"]
